# Although this workflow is identical to the Prefetching Library, since they are different projects it might be better to keep then separate.
name: Sample app Weather and News 

on:
  push:
    paths:
      - "Test-App/Weather-and-News-app/**"
  pull_request:
    branches: [master]
    paths:
      - "Test-App/Weather-and-News-app/**"

jobs:
  build:
    name: Build Weather and News app
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run SonnarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_KEY }}
        run: ./gradlew sonarqube -PnappaSonarLogin=${{ secrets.SONAR_KEY }} -PnappaSonarOrganization=${{ secrets.SONAR_ORGANIZATION }}
        continue-on-error: true
    defaults:
      run:
        shell: bash
        working-directory: Test-App/Weather-and-News-app/
