name: CI/CD - Plugin for Android Studio

on:
  push:
    paths:
      - "Android-Studio-Plugin/**"
  pull_request:
    branches: [master]
    paths:
      - "Android-Studio-Plugin/**"

jobs:
  build:
    name: Build Plugin
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
        run: ./gradlew buildPlugin
    defaults:
      run:
        shell: bash
        working-directory: Android-Studio-Plugin/
